.\" $Id: wtfm_example.man 57 2005-09-08 19:45:22Z branden $
.\" This manpage is in the public domain.
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.TH gizmo 1 2005-07-09 "Gizmo 1.0"
.SH NAME
gizmo \- GNU frob bletcher
.
.SH SYNOPSIS
.B update\-gizmo
[
.I options
]
.I command
.IR file " ..."
.br
.BR "tar " { " create " | " list " |
.BR " extract " }
.br
.BR "gizmo " [ " \-ABCabc " ]
.RB { " see " | " hear " | " smell " }
.br
.BR "gizmo " { " \-\-help " | " \-\-version " }
.SH DESCRIPTION
One two
.br
three.
.br
\&. This line begins with a dot.
"\(rsn" often indicates a newline.
.PP
See spot runs!\" XXX: Fix grammar.
.\" This is a comment on a line by itself.
.SH AUTHOR
Copyright \(co 2005 Quux \fIItalics\fP Inc
.br
.URL "http://www.debian.org" "Debian" "*"
